[package]
name = "opti-radar"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[lib]
name = "opti_radar"
path = "src/lib.rs"

[[bin]]
name = "opti_radar_main"
path = "src/main.rs"

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"